language: php

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        - php: 7.2
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs --standard=PSR12 src tests
    - ./vendor/bin/phpstan analyse --level=max src tests
