language: php

php:
    - 7.4
    - 8.0
    - 8.1

matrix:
    include:
        - php: 7.4
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs src tests
    - vendor/bin/phpstan analyse --level=max src tests
